// Code generated by goyacc -l -o parser.go parser.go.y. DO NOT EDIT.
//
// go.sh/parser :: parser.go
//
//   Copyright (c) 2018 Akinori Hattori <hattya@gmail.com>
//
//   Permission is hereby granted, free of charge, to any person
//   obtaining a copy of this software and associated documentation files
//   (the "Software"), to deal in the Software without restriction,
//   including without limitation the rights to use, copy, modify, merge,
//   publish, distribute, sublicense, and/or sell copies of the Software,
//   and to permit persons to whom the Software is furnished to do so,
//   subject to the following conditions:
//
//   The above copyright notice and this permission notice shall be
//   included in all copies or substantial portions of the Software.
//
//   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
//   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
//   BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
//   ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
//   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//   SOFTWARE.
//

package parser

import __yyfmt__ "fmt"

import (
	"bufio"
	"bytes"
	"errors"
	"io"
	"strings"

	"github.com/hattya/go.sh/ast"
)

type yySymType struct {
	yys      int
	list     ast.List
	and_or   *ast.AndOrList
	pipeline *ast.Pipeline
	cmd      *ast.Cmd
	expr     ast.CmdExpr
	token    token
	elt      *element
	item     *ast.CaseItem
	items    []*ast.CaseItem
	else_    []ast.ElsePart
	cmds     []ast.Command
	redir    *ast.Redir
	redirs   []*ast.Redir
	word     ast.Word
	words    []ast.Word
}

const AND = 57346
const OR = 57347
const LAE = 57348
const RAE = 57349
const BREAK = 57350
const CLOBBER = 57351
const APPEND = 57352
const DUPIN = 57353
const DUPOUT = 57354
const RDWR = 57355
const IO_NUMBER = 57356
const WORD = 57357
const NAME = 57358
const ASSIGNMENT_WORD = 57359
const Bang = 57360
const Lbrace = 57361
const Rbrace = 57362
const For = 57363
const Case = 57364
const Esac = 57365
const In = 57366
const If = 57367
const Elif = 57368
const Then = 57369
const Else = 57370
const Fi = 57371
const While = 57372
const Until = 57373
const Do = 57374
const Done = 57375

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"AND",
	"OR",
	"'|'",
	"'('",
	"')'",
	"LAE",
	"RAE",
	"BREAK",
	"'&'",
	"';'",
	"'<'",
	"'>'",
	"CLOBBER",
	"APPEND",
	"DUPIN",
	"DUPOUT",
	"RDWR",
	"IO_NUMBER",
	"WORD",
	"NAME",
	"ASSIGNMENT_WORD",
	"Bang",
	"Lbrace",
	"Rbrace",
	"For",
	"Case",
	"Esac",
	"In",
	"If",
	"Elif",
	"Then",
	"Else",
	"Fi",
	"While",
	"Until",
	"Do",
	"Done",
	"'\\n'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

func init() {
	yyErrorVerbose = true

	for i, s := range yyToknames {
		switch s {
		case "$end":
			s = "EOF"
		case "AND":
			s = "'&&'"
		case "OR":
			s = "'||'"
		case "LAE":
			s = "(("
		case "RAE":
			s = "))"
		case "BREAK":
			s = "';;'"
		case "CLOBBER":
			s = "'>|'"
		case "APPEND":
			s = "'>>'"
		case "DUPIN":
			s = "'<&'"
		case "DUPOUT":
			s = "'>&'"
		case "RDWR":
			s = "'<>'"
		case "Bang":
			s = "'!'"
		case "Lbrace":
			s = "'{'"
		case "Rbrace":
			s = "'}'"
		case "For":
			s = "'for'"
		case "Case":
			s = "'case'"
		case "Esac":
			s = "'esac'"
		case "In":
			s = "'in'"
		case "If":
			s = "'if'"
		case "Elif":
			s = "'elif'"
		case "Then":
			s = "'then'"
		case "Else":
			s = "'else'"
		case "Fi":
			s = "'fi'"
		case "While":
			s = "'while'"
		case "Until":
			s = "'until'"
		case "Do":
			s = "'do'"
		case "Done":
			s = "'done'"
		}
		yyToknames[i] = s
	}
}

type element struct {
	redirs  []*ast.Redir
	assigns []*ast.Assign
	args    []ast.Word
}

func extract(cmd *ast.AndOrList) ast.Command {
	switch {
	case len(cmd.List) != 0 || !cmd.SepPos.IsZero():
		return cmd
	case !cmd.Pipeline.Bang.IsZero() || len(cmd.Pipeline.List) != 0:
		return cmd.Pipeline
	}
	return cmd.Pipeline.Cmd
}

func assign(w ast.Word) *ast.Assign {
	k := w[0].(*ast.Lit)
	i := strings.IndexRune(k.Value, '=')
	v := w[1:]
	if i < len(k.Value)-1 {
		v = append(ast.Word{
			&ast.Lit{
				ValuePos: ast.NewPos(k.ValuePos.Line(), k.ValuePos.Col()+i+1),
				Value:    k.Value[i+1:],
			},
		}, v...)
		k.Value = k.Value[:i]
	}
	return &ast.Assign{
		Symbol: k,
		Op:     "=",
		Value:  v,
	}
}

// ParseCommand parses src and returns a command.
func ParseCommand(name string, src interface{}) (ast.Command, []*ast.Comment, error) {
	r, err := open(src)
	if err != nil {
		return nil, nil, err
	}

	l := newLexer(name, r)
	yyParse(l)
	return l.cmd, l.comments, l.err
}

func open(src interface{}) (r io.RuneScanner, err error) {
	switch src := src.(type) {
	case []byte:
		r = bytes.NewReader(src)
	case string:
		r = strings.NewReader(src)
	case io.RuneScanner:
		r = src
	case io.Reader:
		r = bufio.NewReader(src)
	default:
		err = errors.New("invalid source")
	}
	return
}

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 92,
	39, 93,
	-2, 96,
}

const yyPrivate = 57344

const yyLast = 302

var yyAct = [...]int{

	59, 58, 134, 133, 120, 22, 132, 49, 60, 89,
	63, 83, 3, 9, 7, 50, 42, 52, 55, 54,
	91, 61, 4, 84, 157, 150, 126, 62, 24, 87,
	26, 67, 68, 69, 124, 35, 36, 37, 38, 39,
	40, 41, 33, 12, 21, 23, 6, 25, 61, 27,
	28, 91, 91, 29, 72, 76, 123, 55, 30, 31,
	78, 64, 75, 24, 113, 26, 90, 93, 73, 74,
	141, 77, 43, 44, 92, 127, 102, 88, 137, 61,
	61, 97, 25, 78, 27, 28, 96, 95, 29, 149,
	101, 100, 104, 30, 31, 94, 106, 107, 108, 99,
	112, 61, 32, 145, 114, 121, 118, 122, 119, 105,
	111, 110, 117, 115, 116, 121, 50, 122, 125, 103,
	85, 86, 65, 138, 139, 117, 128, 135, 154, 140,
	135, 76, 136, 87, 144, 71, 70, 143, 148, 66,
	64, 166, 136, 151, 159, 136, 81, 152, 153, 80,
	142, 156, 57, 129, 43, 44, 160, 161, 47, 163,
	164, 162, 147, 147, 155, 146, 167, 168, 24, 1,
	26, 98, 165, 45, 46, 35, 36, 37, 38, 39,
	40, 41, 33, 12, 21, 23, 6, 25, 5, 27,
	28, 34, 82, 29, 131, 48, 130, 109, 30, 31,
	24, 20, 26, 19, 158, 18, 17, 35, 36, 37,
	38, 39, 40, 41, 33, 12, 21, 23, 6, 25,
	16, 27, 28, 15, 14, 29, 24, 13, 26, 11,
	30, 31, 8, 35, 36, 37, 38, 39, 40, 41,
	33, 12, 21, 23, 10, 25, 2, 27, 28, 0,
	0, 29, 0, 0, 0, 0, 30, 31, 35, 36,
	37, 38, 39, 40, 41, 33, 51, 0, 53, 35,
	36, 37, 38, 39, 40, 41, 33, 79, 35, 36,
	37, 38, 39, 40, 41, 33, 56, 35, 36, 37,
	38, 39, 40, 41, 33, 35, 36, 37, 38, 39,
	40, 41,
}
var yyPact = [...]int{

	21, -1000, 142, 169, -1000, 152, 219, -1000, -1000, 273,
	-1000, 244, 264, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 145, -1000, -1000, -20, -20, 118, 99, 117, -20,
	-20, -20, -1000, 281, 113, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 21, -1000, -1000, 21, 21, 219, 152, 273,
	-1000, 264, -1000, -1000, 255, -1000, -1000, 141, 138, 21,
	-18, -1000, 93, 111, -1000, 38, -20, 61, 48, 47,
	-1000, -1000, 169, -1000, -1000, -1000, -1000, 255, -1000, -1000,
	-20, -1000, 60, 169, -1000, -1000, -1000, -1000, -20, 37,
	88, -20, -18, 78, -20, -20, -20, 56, 21, -20,
	-18, 24, -20, 39, -1000, -20, 72, 16, -6, -1000,
	273, 169, -1000, -1000, -14, 36, 7, -18, 123, -1000,
	42, -20, -20, -1000, -1000, 273, -1000, -20, 31, -1000,
	120, 73, -1000, -1000, 157, 110, -1000, -1000, 55, -1000,
	-15, -20, -1000, -1000, -1000, -1000, -20, 106, 156, -20,
	-1000, -16, 193, 133, -1000, -20, 82, -1000, -20, -20,
	161, 130, -1000, -1000, -1000, -20, -20, -1000, -1000,
}
var yyPgo = [...]int{

	0, 246, 11, 22, 188, 14, 244, 232, 229, 19,
	13, 227, 224, 223, 220, 206, 205, 203, 201, 197,
	10, 2, 6, 3, 196, 194, 4, 1, 192, 5,
	102, 7, 191, 171, 9, 16, 169, 0, 8,
}
var yyR1 = [...]int{

	0, 36, 36, 36, 1, 1, 2, 2, 2, 3,
	3, 4, 4, 5, 5, 5, 5, 7, 7, 7,
	7, 7, 8, 8, 8, 8, 9, 9, 9, 9,
	10, 10, 10, 10, 10, 10, 10, 10, 11, 12,
	13, 14, 14, 14, 14, 20, 20, 15, 15, 15,
	24, 24, 22, 22, 22, 22, 25, 25, 23, 23,
	23, 23, 21, 21, 16, 16, 26, 26, 26, 17,
	18, 6, 19, 19, 27, 27, 28, 28, 31, 31,
	29, 29, 30, 32, 32, 32, 32, 32, 32, 32,
	33, 33, 34, 34, 35, 35, 37, 37, 38, 38,
}
var yyR2 = [...]int{

	0, 2, 1, 0, 1, 3, 1, 3, 3, 1,
	2, 1, 3, 1, 1, 2, 1, 3, 2, 1,
	2, 1, 1, 2, 1, 2, 1, 2, 1, 2,
	1, 1, 1, 1, 1, 1, 1, 1, 3, 3,
	3, 5, 6, 8, 9, 1, 2, 6, 7, 7,
	1, 2, 5, 5, 6, 6, 1, 2, 3, 3,
	4, 4, 1, 3, 5, 6, 4, 5, 2, 5,
	5, 5, 1, 2, 3, 2, 1, 3, 1, 2,
	1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
	2, 1, 2, 1, 1, 1, 1, 0, 1, 2,
}
var yyChk = [...]int{

	-1000, -36, -1, -2, -3, -4, 25, -5, -7, -10,
	-6, -8, 22, -11, -12, -13, -14, -15, -16, -17,
	-18, 23, -29, 24, 7, 26, 9, 28, 29, 32,
	37, 38, -30, 21, -32, 14, 15, 16, 17, 18,
	19, 20, -35, 12, 13, 4, 5, 6, -4, -31,
	-29, 22, -29, 24, -9, -29, 22, 7, -27, -37,
	-38, 41, -27, -20, 22, 23, 22, -27, -27, -27,
	-30, 22, -2, -3, -3, -5, -29, -9, -29, 22,
	8, 8, -28, -2, 41, 27, 10, 22, 39, -34,
	-37, 13, -38, -37, 34, 39, 39, -37, -33, -35,
	-38, -27, 39, 31, -37, 31, -27, -27, -27, -19,
	-10, -2, -37, 40, -27, -34, -20, -38, -37, 36,
	-26, 33, 35, 40, 40, -31, 40, 39, -34, 30,
	-24, -25, -22, -23, -21, 7, 22, 36, -27, -27,
	-27, 39, 30, -22, -23, 30, 8, 6, -21, 34,
	40, -27, -37, -27, 22, 8, -27, 40, 11, 11,
	-37, -27, -26, -37, -37, 11, 11, -37, -37,
}
var yyDef = [...]int{

	3, -2, 2, 4, 6, 9, 0, 11, 13, 14,
	16, 19, 21, 30, 31, 32, 33, 34, 35, 36,
	37, 0, 22, 24, 97, 97, 0, 0, 0, 97,
	97, 97, 80, 0, 0, 83, 84, 85, 86, 87,
	88, 89, 1, 94, 95, 0, 0, 0, 10, 15,
	78, 18, 23, 25, 20, 26, 28, 0, 0, 0,
	96, 98, 0, 0, 45, 97, 97, 0, 0, 0,
	81, 82, 5, 7, 8, 12, 79, 17, 27, 29,
	97, 38, 75, 76, 99, 39, 40, 46, 97, 0,
	0, 97, -2, 0, 97, 97, 97, 0, 74, 97,
	91, 0, 97, 0, 92, 97, 0, 0, 0, 71,
	72, 77, 90, 41, 0, 0, 0, 93, 0, 64,
	0, 97, 97, 69, 70, 73, 42, 97, 0, 47,
	0, 0, 50, 56, 0, 0, 62, 65, 0, 68,
	0, 97, 48, 51, 57, 49, 97, 0, 0, 97,
	43, 0, 58, 59, 63, 97, 66, 44, 97, 97,
	60, 61, 67, 52, 53, 97, 97, 54, 55,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	41, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 12, 3,
	7, 8, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 13,
	14, 3, 15, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 6,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 9, 10, 11, 16, 17, 18,
	19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
	29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
	39, 40,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			ao := yyDollar[1].list[len(yyDollar[1].list)-1]
			ao.SepPos = yyDollar[2].token.pos
			ao.Sep = yyDollar[2].token.val
			if len(yyDollar[1].list) > 1 {
				yylex.(*lexer).cmd = yyDollar[1].list
			} else {
				yylex.(*lexer).cmd = extract(yyDollar[1].list[0])
			}
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if len(yyDollar[1].list) > 1 {
				yylex.(*lexer).cmd = yyDollar[1].list
			} else {
				yylex.(*lexer).cmd = extract(yyDollar[1].list[0])
			}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.list = append(yyVAL.list, yyDollar[1].and_or)
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			ao := yyVAL.list[len(yyVAL.list)-1]
			ao.SepPos = yyDollar[2].token.pos
			ao.Sep = yyDollar[2].token.val
			yyVAL.list = append(yyVAL.list, yyDollar[3].and_or)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.and_or = &ast.AndOrList{Pipeline: yyDollar[1].pipeline}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.and_or.List = append(yyVAL.and_or.List, &ast.AndOr{
				OpPos:    yyDollar[2].token.pos,
				Op:       yyDollar[2].token.val,
				Pipeline: yyDollar[3].pipeline,
			})
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.and_or.List = append(yyVAL.and_or.List, &ast.AndOr{
				OpPos:    yyDollar[2].token.pos,
				Op:       yyDollar[2].token.val,
				Pipeline: yyDollar[3].pipeline,
			})
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.pipeline = yyDollar[2].pipeline
			yyVAL.pipeline.Bang = yyDollar[1].token.pos
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.pipeline = &ast.Pipeline{Cmd: yyDollar[1].cmd}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.pipeline.List = append(yyVAL.pipeline.List, &ast.Pipe{
				OpPos: yyDollar[2].token.pos,
				Op:    yyDollar[2].token.val,
				Cmd:   yyDollar[3].cmd,
			})
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.cmd = &ast.Cmd{
				Expr: &ast.SimpleCmd{
					Assigns: yyDollar[1].elt.assigns,
					Args:    yyDollar[1].elt.args,
				},
				Redirs: yyDollar[1].elt.redirs,
			}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.cmd = &ast.Cmd{Expr: yyDollar[1].expr}
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.cmd = &ast.Cmd{
				Expr:   yyDollar[1].expr,
				Redirs: yyDollar[2].redirs,
			}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.elt = &element{
				redirs:  append(yyDollar[1].elt.redirs, yyDollar[3].elt.redirs...),
				assigns: yyDollar[1].elt.assigns,
			}
			yyVAL.elt.args = append(yyVAL.elt.args, yyDollar[2].word)
			yyVAL.elt.args = append(yyVAL.elt.args, yyDollar[3].elt.args...)
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.elt = yyDollar[1].elt
			yyVAL.elt.args = append(yyVAL.elt.args, yyDollar[2].word)
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.elt = &element{redirs: yyDollar[2].elt.redirs}
			yyVAL.elt.args = append(yyVAL.elt.args, yyDollar[1].word)
			yyVAL.elt.args = append(yyVAL.elt.args, yyDollar[2].elt.args...)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.elt = new(element)
			yyVAL.elt.args = append(yyVAL.elt.args, yyDollar[1].word)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.elt = new(element)
			yyVAL.elt.redirs = append(yyVAL.elt.redirs, yyDollar[1].redir)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.elt.redirs = append(yyVAL.elt.redirs, yyDollar[2].redir)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.elt = new(element)
			yyVAL.elt.assigns = append(yyVAL.elt.assigns, assign(yyDollar[1].word))
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.elt.assigns = append(yyVAL.elt.assigns, assign(yyDollar[2].word))
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.elt = new(element)
			yyVAL.elt.redirs = append(yyVAL.elt.redirs, yyDollar[1].redir)
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.elt.redirs = append(yyVAL.elt.redirs, yyDollar[2].redir)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.elt = new(element)
			yyVAL.elt.args = append(yyVAL.elt.args, yyDollar[1].word)
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.elt.args = append(yyVAL.elt.args, yyDollar[2].word)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &ast.Subshell{
				Lparen: yyDollar[1].token.pos,
				List:   yyDollar[2].cmds,
				Rparen: yyDollar[3].token.pos,
			}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &ast.Group{
				Lbrace: yyDollar[1].token.pos,
				List:   yyDollar[2].cmds,
				Rbrace: yyDollar[3].token.pos,
			}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &ast.ArithEval{
				Left:  yyDollar[1].token.pos,
				Expr:  yyDollar[2].words,
				Right: yyDollar[3].token.pos,
			}
		}
	case 41:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.expr = &ast.ForClause{
				For:  yyDollar[1].token.pos,
				Name: yyDollar[2].word[0].(*ast.Lit),
				Do:   yyDollar[3].token.pos,
				List: yyDollar[4].cmds,
				Done: yyDollar[5].token.pos,
			}
		}
	case 42:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.expr = &ast.ForClause{
				For:       yyDollar[1].token.pos,
				Name:      yyDollar[2].word[0].(*ast.Lit),
				Semicolon: yyDollar[3].token.pos,
				Do:        yyDollar[4].token.pos,
				List:      yyDollar[5].cmds,
				Done:      yyDollar[6].token.pos,
			}
		}
	case 43:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.expr = &ast.ForClause{
				For:       yyDollar[1].token.pos,
				Name:      yyDollar[2].word[0].(*ast.Lit),
				In:        yyDollar[4].token.pos,
				Semicolon: yyDollar[5].token.pos,
				Do:        yyDollar[6].token.pos,
				List:      yyDollar[7].cmds,
				Done:      yyDollar[8].token.pos,
			}
		}
	case 44:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.expr = &ast.ForClause{
				For:       yyDollar[1].token.pos,
				Name:      yyDollar[2].word[0].(*ast.Lit),
				In:        yyDollar[4].token.pos,
				Items:     yyDollar[5].words,
				Semicolon: yyDollar[6].token.pos,
				Do:        yyDollar[7].token.pos,
				List:      yyDollar[8].cmds,
				Done:      yyDollar[9].token.pos,
			}
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.words = append(yyVAL.words, yyDollar[1].word)
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.words = append(yyVAL.words, yyDollar[2].word)
		}
	case 47:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.expr = &ast.CaseClause{
				Case: yyDollar[1].token.pos,
				Word: yyDollar[2].word,
				In:   yyDollar[4].token.pos,
				Esac: yyDollar[6].token.pos,
			}
		}
	case 48:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.expr = &ast.CaseClause{
				Case:  yyDollar[1].token.pos,
				Word:  yyDollar[2].word,
				In:    yyDollar[4].token.pos,
				Items: yyDollar[6].items,
				Esac:  yyDollar[7].token.pos,
			}
		}
	case 49:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.expr = &ast.CaseClause{
				Case:  yyDollar[1].token.pos,
				Word:  yyDollar[2].word,
				In:    yyDollar[4].token.pos,
				Items: yyDollar[6].items,
				Esac:  yyDollar[7].token.pos,
			}
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.items = append(yyVAL.items, yyDollar[1].item)
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.items = append(yyVAL.items, yyDollar[2].item)
		}
	case 52:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.item = &ast.CaseItem{
				Patterns: yyDollar[1].words,
				Rparen:   yyDollar[2].token.pos,
				Break:    yyDollar[4].token.pos,
			}
		}
	case 53:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.item = &ast.CaseItem{
				Patterns: yyDollar[1].words,
				Rparen:   yyDollar[2].token.pos,
				List:     yyDollar[3].cmds,
				Break:    yyDollar[4].token.pos,
			}
		}
	case 54:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.item = &ast.CaseItem{
				Lparen:   yyDollar[1].token.pos,
				Patterns: yyDollar[2].words,
				Rparen:   yyDollar[3].token.pos,
				Break:    yyDollar[5].token.pos,
			}
		}
	case 55:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.item = &ast.CaseItem{
				Lparen:   yyDollar[1].token.pos,
				Patterns: yyDollar[2].words,
				Rparen:   yyDollar[3].token.pos,
				List:     yyDollar[4].cmds,
				Break:    yyDollar[5].token.pos,
			}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.items = append(yyVAL.items, yyDollar[1].item)
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.items = append(yyVAL.items, yyDollar[2].item)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.item = &ast.CaseItem{
				Patterns: yyDollar[1].words,
				Rparen:   yyDollar[2].token.pos,
			}
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.item = &ast.CaseItem{
				Patterns: yyDollar[1].words,
				Rparen:   yyDollar[2].token.pos,
				List:     yyDollar[3].cmds,
			}
		}
	case 60:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.item = &ast.CaseItem{
				Lparen:   yyDollar[1].token.pos,
				Patterns: yyDollar[2].words,
				Rparen:   yyDollar[3].token.pos,
			}
		}
	case 61:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.item = &ast.CaseItem{
				Lparen:   yyDollar[1].token.pos,
				Patterns: yyDollar[2].words,
				Rparen:   yyDollar[3].token.pos,
				List:     yyDollar[4].cmds,
			}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.words = append(yyVAL.words, yyDollar[1].word)
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.words = append(yyVAL.words, yyDollar[3].word)
		}
	case 64:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.expr = &ast.IfClause{
				If:   yyDollar[1].token.pos,
				Cond: yyDollar[2].cmds,
				Then: yyDollar[3].token.pos,
				List: yyDollar[4].cmds,
				Fi:   yyDollar[5].token.pos,
			}
		}
	case 65:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.expr = &ast.IfClause{
				If:   yyDollar[1].token.pos,
				Cond: yyDollar[2].cmds,
				Then: yyDollar[3].token.pos,
				List: yyDollar[4].cmds,
				Else: yyDollar[5].else_,
				Fi:   yyDollar[6].token.pos,
			}
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.else_ = append(yyVAL.else_, &ast.ElifClause{
				Elif: yyDollar[1].token.pos,
				Cond: yyDollar[2].cmds,
				Then: yyDollar[3].token.pos,
				List: yyDollar[4].cmds,
			})
		}
	case 67:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.else_ = append(yyVAL.else_, &ast.ElifClause{
				Elif: yyDollar[1].token.pos,
				Cond: yyDollar[2].cmds,
				Then: yyDollar[3].token.pos,
				List: yyDollar[4].cmds,
			})
			yyVAL.else_ = append(yyVAL.else_, yyDollar[5].else_...)
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.else_ = append(yyVAL.else_, &ast.ElseClause{
				Else: yyDollar[1].token.pos,
				List: yyDollar[2].cmds,
			})
		}
	case 69:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.expr = &ast.WhileClause{
				While: yyDollar[1].token.pos,
				Cond:  yyDollar[2].cmds,
				Do:    yyDollar[3].token.pos,
				List:  yyDollar[4].cmds,
				Done:  yyDollar[5].token.pos,
			}
		}
	case 70:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.expr = &ast.UntilClause{
				Until: yyDollar[1].token.pos,
				Cond:  yyDollar[2].cmds,
				Do:    yyDollar[3].token.pos,
				List:  yyDollar[4].cmds,
				Done:  yyDollar[5].token.pos,
			}
		}
	case 71:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			x := yyDollar[5].expr.(*ast.FuncDef)
			x.Name = yyDollar[1].word[0].(*ast.Lit)
			x.Lparen = yyDollar[2].token.pos
			x.Rparen = yyDollar[3].token.pos
			yyVAL.cmd = &ast.Cmd{Expr: yyDollar[5].expr}
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = &ast.FuncDef{
				Body: &ast.Cmd{
					Expr: yyDollar[1].expr,
				},
			}
		}
	case 73:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &ast.FuncDef{
				Body: &ast.Cmd{
					Expr:   yyDollar[1].expr,
					Redirs: yyDollar[2].redirs,
				},
			}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			l := yyDollar[2].cmds[len(yyDollar[2].cmds)-1].(ast.List)
			if yyDollar[3].token.typ != '\n' {
				ao := l[len(l)-1]
				ao.SepPos = yyDollar[3].token.pos
				ao.Sep = yyDollar[3].token.val
			}
			if len(l) == 1 {
				yyDollar[2].cmds[len(yyDollar[2].cmds)-1] = extract(l[0])
			}
			yyVAL.cmds = yyDollar[2].cmds
		}
	case 75:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			l := yyDollar[2].cmds[len(yyDollar[2].cmds)-1].(ast.List)
			if len(l) == 1 {
				yyDollar[2].cmds[len(yyDollar[2].cmds)-1] = extract(l[0])
			}
			yyVAL.cmds = yyDollar[2].cmds
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.cmds = append(yyVAL.cmds, ast.List{yyDollar[1].and_or})
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			l := yyVAL.cmds[len(yyVAL.cmds)-1].(ast.List)
			if yyDollar[2].token.typ != '\n' {
				ao := l[len(l)-1]
				ao.SepPos = yyDollar[2].token.pos
				ao.Sep = yyDollar[2].token.val
				yyVAL.cmds[len(yyVAL.cmds)-1] = append(l, yyDollar[3].and_or)
			} else {
				if len(l) == 1 {
					yyVAL.cmds[len(yyVAL.cmds)-1] = extract(l[0])
				}
				yyVAL.cmds = append(yyVAL.cmds, ast.List{yyDollar[3].and_or})
			}
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.redirs = append(yyVAL.redirs, yyDollar[1].redir)
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.redirs = append(yyVAL.redirs, yyDollar[2].redir)
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.redir = yyDollar[2].redir
			yyVAL.redir.N = yyDollar[1].word[0].(*ast.Lit)
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.redir = &ast.Redir{
				OpPos: yyDollar[1].token.pos,
				Op:    yyDollar[1].token.val,
				Word:  yyDollar[2].word,
			}
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.token.pos = ast.Pos{}
		}
	}
	goto yystack /* stack new state and value */
}
