// Code generated by goyacc -l -o parser.go parser.go.y. DO NOT EDIT.
//
// go.sh/parser :: parser.go
//
//   Copyright (c) 2018-2021 Akinori Hattori <hattya@gmail.com>
//
//   SPDX-License-Identifier: MIT
//

package parser

import __yyfmt__ "fmt"

import (
	"bufio"
	"bytes"
	"errors"
	"io"
	"strings"

	"github.com/hattya/go.sh/ast"
)

type yySymType struct {
	yys   int
	list  interface{}
	node  ast.Node
	elt   *element
	word  ast.Word
	token token
}

const AND = 57346
const OR = 57347
const LAE = 57348
const RAE = 57349
const BREAK = 57350
const CLOBBER = 57351
const APPEND = 57352
const HEREDOC = 57353
const HEREDOCI = 57354
const DUPIN = 57355
const DUPOUT = 57356
const RDWR = 57357
const IO_NUMBER = 57358
const WORD = 57359
const NAME = 57360
const ASSIGNMENT_WORD = 57361
const Bang = 57362
const Lbrace = 57363
const Rbrace = 57364
const For = 57365
const Case = 57366
const Esac = 57367
const In = 57368
const If = 57369
const Elif = 57370
const Then = 57371
const Else = 57372
const Fi = 57373
const While = 57374
const Until = 57375
const Do = 57376
const Done = 57377

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"AND",
	"OR",
	"'|'",
	"'('",
	"')'",
	"LAE",
	"RAE",
	"BREAK",
	"'&'",
	"';'",
	"'<'",
	"'>'",
	"CLOBBER",
	"APPEND",
	"HEREDOC",
	"HEREDOCI",
	"DUPIN",
	"DUPOUT",
	"RDWR",
	"IO_NUMBER",
	"WORD",
	"NAME",
	"ASSIGNMENT_WORD",
	"Bang",
	"Lbrace",
	"Rbrace",
	"For",
	"Case",
	"Esac",
	"In",
	"If",
	"Elif",
	"Then",
	"Else",
	"Fi",
	"While",
	"Until",
	"Do",
	"Done",
	"'\\n'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

func init() {
	yyErrorVerbose = true

	for i, s := range yyToknames {
		switch s {
		case "$end":
			s = "EOF"
		case "AND":
			s = "'&&'"
		case "OR":
			s = "'||'"
		case "LAE":
			s = "(("
		case "RAE":
			s = "))"
		case "BREAK":
			s = "';;'"
		case "CLOBBER":
			s = "'>|'"
		case "APPEND":
			s = "'>>'"
		case "HEREDOC":
			s = "'<<'"
		case "HEREDOCI":
			s = "'<<-'"
		case "DUPIN":
			s = "'<&'"
		case "DUPOUT":
			s = "'>&'"
		case "RDWR":
			s = "'<>'"
		case "Bang":
			s = "'!'"
		case "Lbrace":
			s = "'{'"
		case "Rbrace":
			s = "'}'"
		case "For":
			s = "'for'"
		case "Case":
			s = "'case'"
		case "Esac":
			s = "'esac'"
		case "In":
			s = "'in'"
		case "If":
			s = "'if'"
		case "Elif":
			s = "'elif'"
		case "Then":
			s = "'then'"
		case "Else":
			s = "'else'"
		case "Fi":
			s = "'fi'"
		case "While":
			s = "'while'"
		case "Until":
			s = "'until'"
		case "Do":
			s = "'do'"
		case "Done":
			s = "'done'"
		}
		yyToknames[i] = s
	}
}

type element struct {
	redirs  []*ast.Redir
	assigns []*ast.Assign
	args    []ast.Word
}

func extract(cmd *ast.AndOrList) ast.Command {
	switch {
	case len(cmd.List) != 0 || !cmd.SepPos.IsZero():
		return cmd
	case !cmd.Pipeline.Bang.IsZero() || len(cmd.Pipeline.List) != 0:
		return cmd.Pipeline
	}
	return cmd.Pipeline.Cmd
}

func assign(w ast.Word) *ast.Assign {
	n := w[0].(*ast.Lit)
	if i := strings.IndexRune(n.Value, '='); 0 < i && i < len(n.Value)-1 {
		w[0] = &ast.Lit{
			ValuePos: ast.NewPos(n.ValuePos.Line(), n.ValuePos.Col()+i+1),
			Value:    n.Value[i+1:],
		}
		n.Value = n.Value[:i]
	} else {
		w = w[1:]
		n.Value = n.Value[:len(n.Value)-1]
	}
	return &ast.Assign{
		Name:  n,
		Op:    "=",
		Value: w,
	}
}

// ParseCommand parses src and returns a command.
func ParseCommand(name string, src interface{}) (ast.Command, []*ast.Comment, error) {
	r, err := open(src)
	if err != nil {
		return nil, nil, err
	}

	l := newLexer(name, r)
	yyParse(l)
	return l.cmd, l.comments, l.err
}

func open(src interface{}) (r io.RuneScanner, err error) {
	switch src := src.(type) {
	case []byte:
		r = bytes.NewReader(src)
	case string:
		r = strings.NewReader(src)
	case io.RuneScanner:
		r = src
	case io.Reader:
		r = bufio.NewReader(src)
	default:
		err = errors.New("invalid source")
	}
	return
}

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 96,
	41, 98,
	-2, 101,
}

const yyPrivate = 57344

const yyLast = 352

var yyAct = [...]int{
	63, 62, 140, 139, 125, 22, 138, 53, 7, 64,
	93, 88, 3, 9, 65, 54, 58, 56, 59, 46,
	24, 95, 26, 4, 95, 95, 89, 66, 163, 156,
	131, 70, 71, 72, 129, 134, 122, 47, 48, 128,
	117, 25, 147, 27, 28, 132, 106, 29, 100, 92,
	99, 65, 30, 31, 65, 65, 143, 155, 77, 81,
	80, 59, 98, 126, 83, 127, 124, 141, 65, 94,
	97, 34, 82, 78, 79, 126, 109, 127, 96, 32,
	107, 141, 151, 90, 142, 160, 101, 68, 83, 142,
	76, 75, 148, 69, 105, 67, 108, 104, 142, 172,
	110, 111, 112, 165, 116, 74, 135, 103, 118, 86,
	123, 47, 48, 73, 115, 114, 91, 121, 119, 153,
	54, 161, 130, 153, 85, 152, 61, 51, 144, 145,
	121, 133, 5, 1, 146, 102, 81, 49, 50, 52,
	150, 36, 35, 149, 154, 87, 137, 136, 120, 157,
	113, 20, 19, 158, 159, 18, 17, 162, 16, 15,
	14, 13, 166, 167, 11, 169, 170, 168, 8, 10,
	2, 0, 173, 174, 24, 0, 26, 0, 171, 0,
	0, 37, 38, 39, 40, 44, 45, 41, 42, 43,
	33, 12, 21, 23, 6, 25, 0, 27, 28, 0,
	0, 29, 0, 0, 0, 0, 30, 31, 24, 0,
	26, 0, 164, 0, 0, 37, 38, 39, 40, 44,
	45, 41, 42, 43, 33, 12, 21, 23, 6, 25,
	0, 27, 28, 0, 0, 29, 24, 0, 26, 0,
	30, 31, 0, 37, 38, 39, 40, 44, 45, 41,
	42, 43, 33, 12, 21, 23, 6, 25, 0, 27,
	28, 0, 0, 29, 24, 0, 26, 0, 30, 31,
	0, 37, 38, 39, 40, 44, 45, 41, 42, 43,
	33, 12, 21, 23, 0, 25, 0, 27, 28, 0,
	0, 29, 0, 0, 0, 0, 30, 31, 37, 38,
	39, 40, 44, 45, 41, 42, 43, 33, 55, 0,
	57, 37, 38, 39, 40, 44, 45, 41, 42, 43,
	33, 84, 37, 38, 39, 40, 44, 45, 41, 42,
	43, 33, 60, 37, 38, 39, 40, 44, 45, 41,
	42, 43, 33, 37, 38, 39, 40, 44, 45, 41,
	42, 43,
}

var yyPact = [...]int{
	229, -1000, 99, 133, -1000, 121, 257, -1000, -1000, 319,
	-1000, 284, 308, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 119, -1000, -1000, -29, -29, 71, 62, 69, -29,
	-29, -29, -1000, 329, -1000, 67, 66, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 229, -1000, -1000, 229,
	229, 257, 121, 319, -1000, 308, -1000, -1000, 297, -1000,
	-1000, 116, 101, 229, -17, -1000, 54, 106, 8, -29,
	26, 9, 7, -1000, -1000, -1000, -1000, 133, -1000, -1000,
	-1000, -1000, 297, -1000, -1000, -29, -1000, 25, 133, -1000,
	-1000, -1000, -29, 5, 47, -29, -17, 43, -29, -29,
	-29, 13, 229, -29, -17, -2, -29, 12, -1000, -29,
	28, -3, -8, -1000, 319, 133, -1000, -1000, -12, 4,
	11, -17, -1000, 74, -1000, 18, -29, -29, -1000, -1000,
	319, -1000, -29, 1, -1000, -1000, 60, 50, -1000, -1000,
	117, 65, -1000, -1000, 21, -1000, -13, -29, -1000, -1000,
	-1000, -1000, -29, 61, 113, -29, -1000, -14, 201, 92,
	-1000, -29, 40, -1000, -29, -29, 167, 88, -1000, -1000,
	-1000, -29, -29, -1000, -1000,
}

var yyPgo = [...]int{
	0, 170, 11, 23, 132, 8, 169, 168, 164, 16,
	13, 161, 160, 159, 158, 156, 155, 152, 151, 150,
	148, 2, 147, 146, 6, 3, 4, 1, 145, 7,
	5, 79, 71, 142, 141, 135, 10, 19, 133, 0,
	9,
}

var yyR1 = [...]int{
	0, 38, 38, 38, 1, 1, 2, 2, 2, 3,
	3, 4, 4, 5, 5, 5, 5, 7, 7, 7,
	7, 7, 8, 8, 8, 8, 9, 9, 9, 9,
	10, 10, 10, 10, 10, 10, 10, 10, 11, 12,
	13, 14, 14, 14, 14, 20, 20, 15, 15, 15,
	22, 22, 24, 24, 24, 24, 23, 23, 25, 25,
	25, 25, 21, 21, 16, 16, 26, 26, 26, 17,
	18, 6, 19, 19, 27, 27, 28, 28, 29, 29,
	30, 30, 30, 30, 31, 33, 33, 33, 33, 33,
	33, 33, 32, 34, 34, 35, 35, 36, 36, 37,
	37, 39, 39, 40, 40,
}

var yyR2 = [...]int{
	0, 2, 1, 0, 1, 3, 1, 3, 3, 1,
	2, 1, 3, 1, 1, 2, 1, 3, 2, 1,
	2, 1, 1, 2, 1, 2, 1, 2, 1, 2,
	1, 1, 1, 1, 1, 1, 1, 1, 3, 3,
	3, 5, 6, 8, 9, 1, 2, 6, 7, 7,
	1, 2, 5, 5, 6, 6, 1, 2, 3, 3,
	4, 4, 1, 3, 5, 6, 4, 5, 2, 5,
	5, 5, 1, 2, 3, 2, 1, 3, 1, 2,
	1, 2, 1, 2, 2, 1, 1, 1, 1, 1,
	1, 1, 2, 1, 1, 2, 1, 2, 1, 1,
	1, 1, 0, 1, 2,
}

var yyChk = [...]int{
	-1000, -38, -1, -2, -3, -4, 27, -5, -7, -10,
	-6, -8, 24, -11, -12, -13, -14, -15, -16, -17,
	-18, 25, -30, 26, 7, 28, 9, 30, 31, 34,
	39, 40, -31, 23, -32, -33, -34, 14, 15, 16,
	17, 20, 21, 22, 18, 19, -37, 12, 13, 4,
	5, 6, -4, -29, -30, 24, -30, 26, -9, -30,
	24, 7, -27, -39, -40, 43, -27, 24, 25, 24,
	-27, -27, -27, -31, -32, 24, 24, -2, -3, -3,
	-5, -30, -9, -30, 24, 8, 8, -28, -2, 43,
	29, 10, 41, -36, -39, 13, -40, -39, 36, 41,
	41, -39, -35, -37, -40, -27, 41, 33, -39, 33,
	-27, -27, -27, -19, -10, -2, -39, 42, -27, -36,
	-20, -40, 24, -39, 38, -26, 35, 37, 42, 42,
	-29, 42, 41, -36, 24, 32, -22, -23, -24, -25,
	-21, 7, 24, 38, -27, -27, -27, 41, 32, -24,
	-25, 32, 8, 6, -21, 36, 42, -27, -39, -27,
	24, 8, -27, 42, 11, 11, -39, -27, -26, -39,
	-39, 11, 11, -39, -39,
}

var yyDef = [...]int{
	3, -2, 2, 4, 6, 9, 0, 11, 13, 14,
	16, 19, 21, 30, 31, 32, 33, 34, 35, 36,
	37, 0, 22, 24, 102, 102, 0, 0, 0, 102,
	102, 102, 80, 0, 82, 0, 0, 85, 86, 87,
	88, 89, 90, 91, 93, 94, 1, 99, 100, 0,
	0, 0, 10, 15, 78, 18, 23, 25, 20, 26,
	28, 0, 0, 0, 101, 103, 0, 0, 102, 102,
	0, 0, 0, 81, 83, 84, 92, 5, 7, 8,
	12, 79, 17, 27, 29, 102, 38, 75, 76, 104,
	39, 40, 102, 0, 0, 102, -2, 0, 102, 102,
	102, 0, 74, 102, 96, 0, 102, 0, 97, 102,
	0, 0, 0, 71, 72, 77, 95, 41, 0, 0,
	0, 98, 45, 0, 64, 0, 102, 102, 69, 70,
	73, 42, 102, 0, 46, 47, 0, 0, 50, 56,
	0, 0, 62, 65, 0, 68, 0, 102, 48, 51,
	57, 49, 102, 0, 0, 102, 43, 0, 58, 59,
	63, 102, 66, 44, 102, 102, 60, 61, 67, 52,
	53, 102, 102, 54, 55,
}

var yyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	43, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 12, 3,
	7, 8, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 13,
	14, 3, 15, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 6,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 9, 10, 11, 16, 17, 18,
	19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
	29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
	39, 40, 41, 42,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			l := yyDollar[1].list.(ast.List)
			ao := l[len(l)-1]
			ao.SepPos = yyDollar[2].token.pos
			ao.Sep = yyDollar[2].token.val
			if len(l) > 1 {
				yylex.(*lexer).cmd = l
			} else {
				yylex.(*lexer).cmd = extract(l[0])
			}
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			l := yyDollar[1].list.(ast.List)
			if len(l) > 1 {
				yylex.(*lexer).cmd = l
			} else {
				yylex.(*lexer).cmd = extract(l[0])
			}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.list = ast.List{yyDollar[1].node.(*ast.AndOrList)}
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			l := yyVAL.list.(ast.List)
			ao := l[len(l)-1]
			ao.SepPos = yyDollar[2].token.pos
			ao.Sep = yyDollar[2].token.val
			yyVAL.list = append(l, yyDollar[3].node.(*ast.AndOrList))
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.AndOrList{Pipeline: yyDollar[1].node.(*ast.Pipeline)}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node.(*ast.AndOrList).List = append(yyVAL.node.(*ast.AndOrList).List, &ast.AndOr{
				OpPos:    yyDollar[2].token.pos,
				Op:       yyDollar[2].token.val,
				Pipeline: yyDollar[3].node.(*ast.Pipeline),
			})
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node.(*ast.AndOrList).List = append(yyVAL.node.(*ast.AndOrList).List, &ast.AndOr{
				OpPos:    yyDollar[2].token.pos,
				Op:       yyDollar[2].token.val,
				Pipeline: yyDollar[3].node.(*ast.Pipeline),
			})
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
			yyVAL.node.(*ast.Pipeline).Bang = yyDollar[1].token.pos
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Pipeline{Cmd: yyDollar[1].node.(*ast.Cmd)}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node.(*ast.Pipeline).List = append(yyVAL.node.(*ast.Pipeline).List, &ast.Pipe{
				OpPos: yyDollar[2].token.pos,
				Op:    yyDollar[2].token.val,
				Cmd:   yyDollar[3].node.(*ast.Cmd),
			})
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Cmd{
				Expr: &ast.SimpleCmd{
					Assigns: yyDollar[1].elt.assigns,
					Args:    yyDollar[1].elt.args,
				},
				Redirs: yyDollar[1].elt.redirs,
			}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.Cmd{Expr: yyDollar[1].node.(ast.CmdExpr)}
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.Cmd{
				Expr:   yyDollar[1].node.(ast.CmdExpr),
				Redirs: yyDollar[2].list.([]*ast.Redir),
			}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.elt = &element{
				redirs:  append(yyDollar[1].elt.redirs, yyDollar[3].elt.redirs...),
				assigns: yyDollar[1].elt.assigns,
				args:    append([]ast.Word{yyDollar[2].word}, yyDollar[3].elt.args...),
			}
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.elt = yyDollar[1].elt
			yyVAL.elt.args = append(yyVAL.elt.args, yyDollar[2].word)
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.elt = &element{
				redirs: yyDollar[2].elt.redirs,
				args:   append([]ast.Word{yyDollar[1].word}, yyDollar[2].elt.args...),
			}
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.elt = &element{args: []ast.Word{yyDollar[1].word}}
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.elt = &element{redirs: []*ast.Redir{yyDollar[1].node.(*ast.Redir)}}
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.elt.redirs = append(yyVAL.elt.redirs, yyDollar[2].node.(*ast.Redir))
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.elt = &element{assigns: []*ast.Assign{assign(yyDollar[1].word)}}
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.elt.assigns = append(yyVAL.elt.assigns, assign(yyDollar[2].word))
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.elt = &element{redirs: []*ast.Redir{yyDollar[1].node.(*ast.Redir)}}
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.elt.redirs = append(yyVAL.elt.redirs, yyDollar[2].node.(*ast.Redir))
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.elt = &element{args: []ast.Word{yyDollar[1].word}}
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.elt.args = append(yyVAL.elt.args, yyDollar[2].word)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.Subshell{
				Lparen: yyDollar[1].token.pos,
				List:   yyDollar[2].list.([]ast.Command),
				Rparen: yyDollar[3].token.pos,
			}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.Group{
				Lbrace: yyDollar[1].token.pos,
				List:   yyDollar[2].list.([]ast.Command),
				Rbrace: yyDollar[3].token.pos,
			}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.ArithEval{
				Left:  yyDollar[1].token.pos,
				Expr:  yyDollar[2].word,
				Right: yyDollar[3].token.pos,
			}
		}
	case 41:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.ForClause{
				For:  yyDollar[1].token.pos,
				Name: yyDollar[2].word[0].(*ast.Lit),
				Do:   yyDollar[3].token.pos,
				List: yyDollar[4].list.([]ast.Command),
				Done: yyDollar[5].token.pos,
			}
		}
	case 42:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.ForClause{
				For:       yyDollar[1].token.pos,
				Name:      yyDollar[2].word[0].(*ast.Lit),
				Semicolon: yyDollar[3].token.pos,
				Do:        yyDollar[4].token.pos,
				List:      yyDollar[5].list.([]ast.Command),
				Done:      yyDollar[6].token.pos,
			}
		}
	case 43:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.ForClause{
				For:       yyDollar[1].token.pos,
				Name:      yyDollar[2].word[0].(*ast.Lit),
				In:        yyDollar[4].token.pos,
				Semicolon: yyDollar[5].token.pos,
				Do:        yyDollar[6].token.pos,
				List:      yyDollar[7].list.([]ast.Command),
				Done:      yyDollar[8].token.pos,
			}
		}
	case 44:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.node = &ast.ForClause{
				For:       yyDollar[1].token.pos,
				Name:      yyDollar[2].word[0].(*ast.Lit),
				In:        yyDollar[4].token.pos,
				Items:     yyDollar[5].list.([]ast.Word),
				Semicolon: yyDollar[6].token.pos,
				Do:        yyDollar[7].token.pos,
				List:      yyDollar[8].list.([]ast.Command),
				Done:      yyDollar[9].token.pos,
			}
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.list = []ast.Word{yyDollar[1].word}
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.list = append(yyVAL.list.([]ast.Word), yyDollar[2].word)
		}
	case 47:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.CaseClause{
				Case: yyDollar[1].token.pos,
				Word: yyDollar[2].word,
				In:   yyDollar[4].token.pos,
				Esac: yyDollar[6].token.pos,
			}
		}
	case 48:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.node = &ast.CaseClause{
				Case:  yyDollar[1].token.pos,
				Word:  yyDollar[2].word,
				In:    yyDollar[4].token.pos,
				Items: yyDollar[6].list.([]*ast.CaseItem),
				Esac:  yyDollar[7].token.pos,
			}
		}
	case 49:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.node = &ast.CaseClause{
				Case:  yyDollar[1].token.pos,
				Word:  yyDollar[2].word,
				In:    yyDollar[4].token.pos,
				Items: yyDollar[6].list.([]*ast.CaseItem),
				Esac:  yyDollar[7].token.pos,
			}
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.list = []*ast.CaseItem{yyDollar[1].node.(*ast.CaseItem)}
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.list = append(yyVAL.list.([]*ast.CaseItem), yyDollar[2].node.(*ast.CaseItem))
		}
	case 52:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.CaseItem{
				Patterns: yyDollar[1].list.([]ast.Word),
				Rparen:   yyDollar[2].token.pos,
				Break:    yyDollar[4].token.pos,
			}
		}
	case 53:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.CaseItem{
				Patterns: yyDollar[1].list.([]ast.Word),
				Rparen:   yyDollar[2].token.pos,
				List:     yyDollar[3].list.([]ast.Command),
				Break:    yyDollar[4].token.pos,
			}
		}
	case 54:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.CaseItem{
				Lparen:   yyDollar[1].token.pos,
				Patterns: yyDollar[2].list.([]ast.Word),
				Rparen:   yyDollar[3].token.pos,
				Break:    yyDollar[5].token.pos,
			}
		}
	case 55:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.CaseItem{
				Lparen:   yyDollar[1].token.pos,
				Patterns: yyDollar[2].list.([]ast.Word),
				Rparen:   yyDollar[3].token.pos,
				List:     yyDollar[4].list.([]ast.Command),
				Break:    yyDollar[5].token.pos,
			}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.list = []*ast.CaseItem{yyDollar[1].node.(*ast.CaseItem)}
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.list = append(yyVAL.list.([]*ast.CaseItem), yyDollar[2].node.(*ast.CaseItem))
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.CaseItem{
				Patterns: yyDollar[1].list.([]ast.Word),
				Rparen:   yyDollar[2].token.pos,
			}
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.CaseItem{
				Patterns: yyDollar[1].list.([]ast.Word),
				Rparen:   yyDollar[2].token.pos,
				List:     yyDollar[3].list.([]ast.Command),
			}
		}
	case 60:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.CaseItem{
				Lparen:   yyDollar[1].token.pos,
				Patterns: yyDollar[2].list.([]ast.Word),
				Rparen:   yyDollar[3].token.pos,
			}
		}
	case 61:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.CaseItem{
				Lparen:   yyDollar[1].token.pos,
				Patterns: yyDollar[2].list.([]ast.Word),
				Rparen:   yyDollar[3].token.pos,
				List:     yyDollar[4].list.([]ast.Command),
			}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.list = []ast.Word{yyDollar[1].word}
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.list = append(yyVAL.list.([]ast.Word), yyDollar[3].word)
		}
	case 64:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.IfClause{
				If:   yyDollar[1].token.pos,
				Cond: yyDollar[2].list.([]ast.Command),
				Then: yyDollar[3].token.pos,
				List: yyDollar[4].list.([]ast.Command),
				Fi:   yyDollar[5].token.pos,
			}
		}
	case 65:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.IfClause{
				If:   yyDollar[1].token.pos,
				Cond: yyDollar[2].list.([]ast.Command),
				Then: yyDollar[3].token.pos,
				List: yyDollar[4].list.([]ast.Command),
				Else: yyDollar[5].list.([]ast.ElsePart),
				Fi:   yyDollar[6].token.pos,
			}
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.list = []ast.ElsePart{&ast.ElifClause{
				Elif: yyDollar[1].token.pos,
				Cond: yyDollar[2].list.([]ast.Command),
				Then: yyDollar[3].token.pos,
				List: yyDollar[4].list.([]ast.Command),
			}}
		}
	case 67:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.list = append([]ast.ElsePart{&ast.ElifClause{
				Elif: yyDollar[1].token.pos,
				Cond: yyDollar[2].list.([]ast.Command),
				Then: yyDollar[3].token.pos,
				List: yyDollar[4].list.([]ast.Command),
			}}, yyDollar[5].list.([]ast.ElsePart)...)
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.list = []ast.ElsePart{&ast.ElseClause{
				Else: yyDollar[1].token.pos,
				List: yyDollar[2].list.([]ast.Command),
			}}
		}
	case 69:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.WhileClause{
				While: yyDollar[1].token.pos,
				Cond:  yyDollar[2].list.([]ast.Command),
				Do:    yyDollar[3].token.pos,
				List:  yyDollar[4].list.([]ast.Command),
				Done:  yyDollar[5].token.pos,
			}
		}
	case 70:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.UntilClause{
				Until: yyDollar[1].token.pos,
				Cond:  yyDollar[2].list.([]ast.Command),
				Do:    yyDollar[3].token.pos,
				List:  yyDollar[4].list.([]ast.Command),
				Done:  yyDollar[5].token.pos,
			}
		}
	case 71:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			x := yyDollar[5].node.(*ast.FuncDef)
			x.Name = yyDollar[1].word[0].(*ast.Lit)
			x.Lparen = yyDollar[2].token.pos
			x.Rparen = yyDollar[3].token.pos
			yyVAL.node = &ast.Cmd{Expr: yyDollar[5].node.(ast.CmdExpr)}
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.FuncDef{
				Body: &ast.Cmd{
					Expr: yyDollar[1].node.(ast.CmdExpr),
				},
			}
		}
	case 73:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.FuncDef{
				Body: &ast.Cmd{
					Expr:   yyDollar[1].node.(ast.CmdExpr),
					Redirs: yyDollar[2].list.([]*ast.Redir),
				},
			}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			cmds := yyDollar[2].list.([]ast.Command)
			l := cmds[len(cmds)-1].(ast.List)
			if yyDollar[3].token.typ != '\n' {
				ao := l[len(l)-1]
				ao.SepPos = yyDollar[3].token.pos
				ao.Sep = yyDollar[3].token.val
			}
			if len(l) == 1 {
				cmds[len(cmds)-1] = extract(l[0])
			}
			yyVAL.list = yyDollar[2].list
		}
	case 75:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			cmds := yyDollar[2].list.([]ast.Command)
			l := cmds[len(cmds)-1].(ast.List)
			if len(l) == 1 {
				cmds[len(cmds)-1] = extract(l[0])
			}
			yyVAL.list = yyDollar[2].list
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.list = []ast.Command{ast.List{yyDollar[1].node.(*ast.AndOrList)}}
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			cmds := yyVAL.list.([]ast.Command)
			l := cmds[len(cmds)-1].(ast.List)
			if yyDollar[2].token.typ != '\n' {
				ao := l[len(l)-1]
				ao.SepPos = yyDollar[2].token.pos
				ao.Sep = yyDollar[2].token.val
				cmds[len(cmds)-1] = append(l, yyDollar[3].node.(*ast.AndOrList))
			} else {
				if len(l) == 1 {
					cmds[len(cmds)-1] = extract(l[0])
				}
				yyVAL.list = append(cmds, ast.List{yyDollar[3].node.(*ast.AndOrList)})
			}
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.list = []*ast.Redir{yyDollar[1].node.(*ast.Redir)}
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.list = append(yyVAL.list.([]*ast.Redir), yyDollar[2].node.(*ast.Redir))
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
			yyVAL.node.(*ast.Redir).N = yyDollar[1].word[0].(*ast.Lit)
		}
	case 83:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
			yyVAL.node.(*ast.Redir).N = yyDollar[1].word[0].(*ast.Lit)
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.Redir{
				OpPos: yyDollar[1].token.pos,
				Op:    yyDollar[1].token.val,
				Word:  yyDollar[2].word,
			}
		}
	case 92:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.Redir{
				OpPos: yyDollar[1].token.pos,
				Op:    yyDollar[1].token.val,
				Word:  yyDollar[2].word,
			}
			yylex.(*lexer).heredoc.push(yyVAL.node.(*ast.Redir))
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.token.pos = ast.Pos{}
		}
	}
	goto yystack /* stack new state and value */
}
